-- Extend audit entity types for document vault + checklists.

ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'EMPLOYEE_FILE';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'CHECKLIST_TEMPLATE';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'CHECKLIST_INSTANCE';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'CHECKLIST_ITEM_INSTANCE';

