packages:
  - apps/*
  - '!apps/archived'
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - puppeteer
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
