name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: progami/shared-workflows/.github/workflows/ci-base.yml@main
    with:
      node-version: '18'
      run-type-check: false  # No TypeScript in this project
      build-env: |
        {
          "NODE_ENV": "production"
        }