name: CI - Master Repo

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  # PR validation (only on PRs)
  pr-checks:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared/pr-checks.yml@main
    with:
      check-pr-title: true
      add-size-labels: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Main CI pipeline
  ci:
    uses: ./.github/workflows/shared/ci-base.yml@main
    with:
      node-version: '18'
      run-type-check: false  # No TypeScript in master repo yet
      run-security: false    # Enable when ready
      run-e2e: false        # Enable when E2E tests are added
      build-env: |
        {
          "NODE_ENV": "production"
        }

  # Notify on completion
  notify:
    needs: [ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: CI Status
        run: |
          if [ "${{ needs.ci.result }}" == "success" ]; then
            echo "✅ CI passed for master repository"
          else
            echo "❌ CI failed for master repository"
            exit 1
          fi