name: Deploy - Master Repo

on:
  workflow_run:
    workflows: ["CI - Master Repo"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/shared/deploy-ssh.yml@main
    with:
      environment: ${{ github.event.inputs.environment || 'production' }}
      app-name: 'ecom-os'
      app-path: '/home/ecom-os'
      branch: 'main'
      health-check-url: 'https://targonglobal.com'
      node-version: '18'
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}