name: Quick UI Tests

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  quick-test:
    name: Quick UI Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium
      
      - name: Start app and run quick tests
        run: |
          npm run dev &
          npx wait-on http://localhost:3006
          
          # Run only the most stable tests for quick feedback
          npx playwright test tests/e2e/exhaustive-ui-test.spec.ts \
            --grep "should test add employee button|should test search functionality|should test export button|should test form buttons|should test back navigation" \
            --project=chromium \
            --reporter=github
        env:
          CI: true
      
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: test-results/
          retention-days: 1