-- Add serial employeeNumber and standardize employeeId formatting.
--
-- Goals:
-- - Introduce `employeeNumber` as the canonical serial identifier (unique, auto-increment).
-- - Standardize `employeeId` to `EMP-<zero-padded>` derived from employeeNumber.
-- - Backfill existing rows deterministically (createdAt, id order), preserving the current max numeric id when possible.

-- 1) Add column (nullable for backfill)
ALTER TABLE "Employee" ADD COLUMN "employeeNumber" INTEGER;

-- 2) Backfill employeeNumber with a contiguous range ordered by creation time.
--    If existing employeeIds contain numeric parts, keep the max number as the end of the range.
WITH parsed AS (
  SELECT
    "id",
    NULLIF(regexp_replace("employeeId", '[^0-9]', '', 'g'), '')::INTEGER AS parsed_num,
    "createdAt"
  FROM "Employee"
),
stats AS (
  SELECT
    COALESCE(MAX(parsed_num), 0) AS max_num,
    COUNT(*) AS total
  FROM parsed
),
ordered AS (
  SELECT
    "id",
    ROW_NUMBER() OVER (ORDER BY "createdAt", "id") AS rn
  FROM parsed
),
base AS (
  SELECT GREATEST(1, (SELECT max_num FROM stats) - (SELECT total FROM stats) + 1) AS start_num
)
UPDATE "Employee" e
SET "employeeNumber" = (SELECT start_num FROM base) + o.rn - 1
FROM ordered o
WHERE e."id" = o."id";

-- 3) Normalize employeeId to EMP-<zero-padded employeeNumber> (min width 4, never truncate).
UPDATE "Employee"
SET "employeeId" = 'EMP-' || LPAD(
  "employeeNumber"::TEXT,
  GREATEST(4, LENGTH("employeeNumber"::TEXT)),
  '0'
);

-- 4) Enforce constraints and auto-increment for new rows.
ALTER TABLE "Employee" ALTER COLUMN "employeeNumber" SET NOT NULL;
CREATE UNIQUE INDEX "Employee_employeeNumber_key" ON "Employee"("employeeNumber");

ALTER TABLE "Employee"
  ALTER COLUMN "employeeNumber" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Ensure identity sequence continues from the current max.
SELECT setval(
  pg_get_serial_sequence('"Employee"', 'employeeNumber'),
  (SELECT COALESCE(MAX("employeeNumber"), 0) FROM "Employee")
);
