const allTransactions = [
  {
    "Date": "02 Jan 2024",
    "Source": "Spend Money",
    "Description": "Trans Global Freight Management Ltd - CS007 - Batch 6 - Freight",
    "Reference": "INVF529052 - EVER ARM - OOLU0901921 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 572.05,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "6",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "02 Jan 2024",
    "Source": "Spend Money",
    "Description": "Trans Global Freight Management Ltd - CS 007 - Batch 6 - Custom Duty",
    "Reference": "DINV262176 - EVER ARM - OOLU0901921 - UK ",
    "Currency": "GBP",
    "Debit (GBP)": 37.09,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "6",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 7 - Freight",
    "Reference": "FMI21917 - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1217.03,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 7 - Freight",
    "Reference": "FMI21917 - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 298.6,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 7 - Freight",
    "Reference": "FMI21917 - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 99.53,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 1 - Freight",
    "Reference": "FMI21917 - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 520.74,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "1",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 1 - Freight",
    "Reference": "FMI21917 - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 556.05,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "1",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 7 - Freight",
    "Reference": "FM40508D - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 508.76,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 7 - Freight",
    "Reference": "FM40508D - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 116.45,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 7 - Freight",
    "Reference": "FM40508D - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 80.73,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "7",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 1 - Freight",
    "Reference": "FM40508D - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 328.39,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "1",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 1 - Freight",
    "Reference": "FM40508D - MSC ELOANE/ 352W - MRKU4430533 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 350.67,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "1",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "18 Mar 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics -  CS 007 - Batch 8 - Freight\n",
    "Reference": "FMI22841 - OOCL GERMANY/ 031W - OOCU8336559 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 2375.56,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "18 Mar 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics -  CS 008 - Batch 8 - Freight",
    "Reference": "FMI22841 - OOCL GERMANY/ 031W - OOCU8336559 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 132.08,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "18 Mar 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics -  CS 009 - Batch 8 - Freight",
    "Reference": "FMI22841 - OOCL GERMANY/ 031W - OOCU8336559 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 998.15,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "18 Mar 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics -  CS 010 - Batch 8 - Freight",
    "Reference": "FMI22841 - OOCL GERMANY/ 031W - OOCU8336559 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 407.44,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 May 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 8 - Custom Duty",
    "Reference": "FM41825D - LL1 OOCL GERMANY - OOCU8336559 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 769.81,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 May 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008 - Batch 8 - Custom Duty",
    "Reference": "FM41825D - LL1 OOCL GERMANY - OOCU8336559 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 55.27,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "13 May 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 8 - Custom Duty",
    "Reference": "FM41825D - LL1 OOCL GERMANY - OOCU8336559 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 343.16,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "13 May 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 8 - Custom Duty",
    "Reference": "FM41825D - LL1 OOCL GERMANY - OOCU8336559 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 252.13,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "8",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 Jun 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 11 - Freight",
    "Reference": "FMI23862 - MSC ILARIA/ 425W - MRKU2605099 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 452.13,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 Jun 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 11 - Freight",
    "Reference": "FMI23862 - MSC ILARIA/ 425W - MRKU2605099 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 5721.0,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 Jun 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 11 - Freight",
    "Reference": "FMI23862 - MSC ILARIA/ 425W - MRKU2605099 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1226.0,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 9 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 494.01,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008 - Batch 9 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 13.69,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 9 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 118.13,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 9 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 56.02,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 2 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 495.79,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 2 - Custom Duty",
    "Reference": "FM42654D - MSC IDANIA - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 661.82,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 9 -\nFreight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1407.21,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008 - Batch 9-\nFreight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 39.0,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 9 - Freight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 336.51,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 9-\nFreight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 159.56,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "9",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 2-\nFreight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1040.11,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "01 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 2-\nFreight",
    "Reference": "FMI23274 - MSC IDANIA 419W - PONU8173841 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1388.43,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "15 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 10 - Freight",
    "Reference": "FMI23444 - OOCL JAPAN 031W - CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 3637.06,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "15 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 10 - Freight",
    "Reference": "FMI23444 - OOCL JAPAN 031W - CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1452.45,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "15 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 2 - Freight",
    "Reference": "FMI23444 - OOCL JAPAN 031W - CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 816.36,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "15 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 10 - Freight",
    "Reference": "FMI23444 - OOCL JAPAN 031W - CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 177.9,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "26 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 2 - Custom Duty",
    "Reference": "FM43190D - LL1 OOCL JAPAN -  CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 223.1,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "26 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 10 - Custom Duty",
    "Reference": "FM43190D - LL1 OOCL JAPAN -  CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 882.44,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "26 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 10 - Custom Duty",
    "Reference": "FM43190D - LL1 OOCL JAPAN -  CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 352.48,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "26 Jul 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 10 - Custom Duty",
    "Reference": "FM43190D - LL1 OOCL JAPAN -  CSNU7428876 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 43.16,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "10",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 007 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 4320.59,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 008 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 287.53,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 009 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1053.7,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 010 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 998.24,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 011 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1296.01,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "29 Jul 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 012 - Batch 12 - Freight",
    "Reference": "VUK00003566 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 575.91,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "09 Aug 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 11 - Custom Duty",
    "Reference": "FM43483D - MSC ILARIA - MRKU2605099 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1203.25,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "09 Aug 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 11 - Custom Duty",
    "Reference": "FM43483D - MSC ILARIA - MRKU2605099 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 257.89,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "09 Aug 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 11 - Custom Duty",
    "Reference": "FM43483D - MSC ILARIA - MRKU2605099 - 40ft HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 95.25,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "11",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 007 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 993.87,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 008 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 66.15,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 009 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 242.43,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 010 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 229.67,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 011 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 298.39,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "16 Sep 2024",
    "Source": "Spend Money",
    "Description": "V Global Logistics - CS 012 - Batch 12 - Custom Duty",
    "Reference": "VUK00003584 - OOCL SPAIN / 006W - OOCU8157379 - 40HC - UK",
    "Currency": "GBP",
    "Debit (GBP)": 132.5,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "17 Sep 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 3 - Freight",
    "Reference": "FM44187 - COPIAPO - FTAU1552236 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 795.65,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "3",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "17 Sep 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 3 - Freight",
    "Reference": "FM44187 - COPIAPO - FTAU1552236 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 3041.89,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "3",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "19 Sep 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 3 - Freight",
    "Reference": "FM44233 - COPIAPO - FTAU1552236 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 34.21,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "3",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "19 Sep 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 002 - Batch 3 - Freight",
    "Reference": "FM44233 - COPIAPO - FTAU1552236 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 130.79,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "3",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "12 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 4 - Freight",
    "Reference": "FM45948 - APL GWANGYANG - ONEU2555534 - 20ft - UK",
    "Currency": "GBP",
    "Debit (GBP)": 1342.22,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "4",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "12 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS CDS 001 - Batch 4 - Freight",
    "Reference": "FM45948 - APL GWANGYANG - ONEU2555534 - 20ft - UK",
    "Currency": "GBP",
    "Debit (GBP)": 2381.43,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "4",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 50.41,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 276.92,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 2010.19,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 011 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 733.37,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 589.65,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "17 Dec 2024",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 012 - Batch 13 - Freight",
    "Reference": "FM46032 - MSC BIANCA SILVIA - TCNU2723703 - UK",
    "Currency": "GBP",
    "Debit (GBP)": 611.82,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 007 - Batch 7 - Production",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 815.12,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 009 - Batch 7 - Production",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 445.89,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 010 - Batch 7 - Production\n",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 396.44,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 007 - Batch 7 - Production\n",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 2996.21,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 009 - Batch 7 - Production\n",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 448.82,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Time Value Limited - CS 010 - Batch 7 - Production\n",
    "Reference": "PH231236 - Time Value Limited",
    "Currency": "GBP",
    "Debit (GBP)": 396.44,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "7",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Hirech Industrial Co Ltd - CS CDS 001 - Batch 1 - Production",
    "Reference": "RECHETX231024-1 - Hirech Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 2692.89,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "1",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "13 Jan 2024",
    "Source": "Spend Money",
    "Description": "Hirech Industrial Co Ltd - CS CDS 002 - Batch 1 - Production",
    "Reference": "RECHETX231024-1 - Hirech Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 2868.93,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "1",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 8 - Packaging label & gift card",
    "Reference": "14345449001037350 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 24.53,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 8 - Production",
    "Reference": "PH240329 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 10782.91,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 008 - Batch 8 - Production",
    "Reference": "PH240329 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 865.95,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 - Batch 8 - Production",
    "Reference": "PH240329 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 4878.17,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 - Batch 8 - Production",
    "Reference": "PH240329 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 4430.48,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "19 Feb 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009 - Batch 8 - Production Gloves",
    "Reference": "202293939501027350 - Huizhou Anboson Technology Co., Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 258.86,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "23 Feb 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007 - Batch 8 - Production Box",
    "Reference": "PI240219 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 1910.3,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "23 Feb 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 008 - Batch 8 - Production Box",
    "Reference": "PI240219 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 67.92,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "23 Feb 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 8 - Production Box",
    "Reference": "PI240219 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 611.88,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "23 Feb 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 010 - Batch 8 - Production Box",
    "Reference": "PI240219 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 132.36,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007 - Batch 9 - Production Box",
    "Reference": "PI240320 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 615.08,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 9 - Production Box",
    "Reference": "PI240320 - Shanghai Yucai Industrial",
    "Currency": "GBP",
    "Debit (GBP)": 156.97,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 9 - Production",
    "Reference": "PI-2403202-1 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 6067.26,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 008 - Batch 9 - Production",
    "Reference": "PI-2403202-1 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 241.59,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 - Batch 9 - Production",
    "Reference": "PI-2403202-1 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 1563.25,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 - Batch 9 - Production",
    "Reference": "PI-2403202-1 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 1648.09,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "20 Mar 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009 - Batch 9 - Production Gloves",
    "Reference": "14765445501037350 - Huizhou Anboson Technology Co., Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 85.99,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "28 Mar 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 007 - Batch 8 - Inspection",
    "Reference": "AZ-RR-35-24 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 103.77,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "28 Mar 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 008 - Batch 8 - Inspection",
    "Reference": "AZ-RR-35-24 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 20.41,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "28 Mar 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 009 - Batch 8 - Inspection",
    "Reference": "AZ-RR-35-24 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 34.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "28 Mar 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 010 - Batch 8 - Inspection",
    "Reference": "AZ-RR-35-24 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 39.36,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "8",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "02 Apr 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co., Ltd. - CS 007 - Batch 9 - Production",
    "Reference": "PI240320 - Shanghai Yucai Industrial Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 625.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "02 Apr 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co., Ltd. - CS 009 - Batch 9 - Production",
    "Reference": "PI240320 - Shanghai Yucai Industrial Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 159.62,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "09 Apr 2024",
    "Source": "Spend Money",
    "Description": "Alibaba - CS 009 - Batch 10 - Production Gloves",
    "Reference": "15007249501037350 - Huizhou Anboson Technology Co., Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 286.39,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "09 Apr 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co., Ltd. - CS 007 - Batch 10 - Production Box",
    "Reference": "PI240409 - Shanghai Yucai Industrial Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 1614.67,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "09 Apr 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co., Ltd. - CS 009 - Batch 10 - Production Box",
    "Reference": "PI240409 - Shanghai Yucai Industrial Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 513.23,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "09 Apr 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co., Ltd. - CS 010 - Batch 10 - Production Box",
    "Reference": "PI240409 - Shanghai Yucai Industrial Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 629.72,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "26 Apr 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu B-Line Tools Co Ltd - CS CDS 001 - Batch 2 - Production",
    "Reference": "BLTE24026R - Jiangsu B-Line Tools Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 7686.86,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "26 Apr 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu B-Line Tools Co Ltd - CS CDS 002 - Batch 2 - Production",
    "Reference": "BLTE24026R - Jiangsu B-Line Tools Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 6965.35,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "2",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 007 - Batch 9 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 9.89,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 008 - Batch 9 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 29.65,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 009 - Batch 9 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 127.92,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 010 - Batch 9 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 31.99,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "9",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS CDS 001 - Batch 2 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 128.21,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "2",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "02 May 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS CDS 002 - Batch 2 - Inspection",
    "Reference": "AZ-RR-37-27 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 71.25,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "2",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "07 May 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007 - Batch 11 - Production Box",
    "Reference": "PI240506 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 2554.22,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "07 May 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 11 - Production Box",
    "Reference": "PI240506 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 673.83,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "07 May 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS010 - Batch 11 - Production Box",
    "Reference": "PI240506 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 37.6,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "08 May 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009 - Batch 11 - Production Gloves",
    "Reference": "21076112200102735 - Huizhou Anboson Technology Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 300.08,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "22 May 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009 - Batch 13 - Production Gloves",
    "Reference": "15559369501037350 - Huizhou Anboson Technology Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 377.5,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "22 May 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 012 - Batch 13 - Production Gloves",
    "Reference": "15559369501037350 - Huizhou Anboson Technology Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 224.5,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "23 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 - Batch 10 - Production",
    "Reference": "PH240526 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 1302.09,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "23 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 10 - Production",
    "Reference": "PH240526 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 11112.16,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "23 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 - Batch 10 - Production",
    "Reference": "PH240526 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 4781.35,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 008 - Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 284.9,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 - Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 2591.28,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 8292.85,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 011 - Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 6727.36,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 - Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 3475.66,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "28 May 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS012 -Batch 12 - Production",
    "Reference": "PH240745 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 4983.23,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "30 May 2024",
    "Source": "Spend Money",
    "Description": "Bari Textiles - CS CDS 001 - Batch 4 - Production",
    "Reference": "BTML-240091-01 - Bari Textiles",
    "Currency": "GBP",
    "Debit (GBP)": 3333.33,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "4",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "30 May 2024",
    "Source": "Spend Money",
    "Description": "Bari Textiles - CS CDS 002 - Batch 4 - Production",
    "Reference": "BTML-240091-01 - Bari Textiles",
    "Currency": "GBP",
    "Debit (GBP)": 5914.16,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "4",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "03 Jun 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 007 - Batch 10  - Inspection",
    "Reference": "AZ-RR-39-29 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 148.09,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "03 Jun 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 009 - Batch 10  - Inspection",
    "Reference": "AZ-RR-39-29 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 37.1,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "03 Jun 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd - CS 010 - Batch 10  - Inspection",
    "Reference": "AZ-RR-39-29 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 10.04,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "10",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 1713.13,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 008 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 16.0,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 402.87,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 010 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 55.44,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 011 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 563.06,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "11 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 012 - Batch 12 - Production Box",
    "Reference": "240522 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 312.71,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "17 Jun 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 - Batch 11 - Production",
    "Reference": "PH240621 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 1497.01,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "17 Jun 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 11 - Production",
    "Reference": "PH240621 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 13997.69,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "17 Jun 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 - Batch 11 - Production",
    "Reference": "PH240621 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 5152.21,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 1943.85,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 008 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 16.9,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 406.96,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 010 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 58.57,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 011 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 462.61,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "26 Jun 2024",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 012 - Batch 13 - Production Box",
    "Reference": "PI240613 - Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 231.3,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "03 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 007 - Batch 11 - Inspection",
    "Reference": "AZ-RR-40-31 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 151.67,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "03 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 009 - Batch 11 - Inspection",
    "Reference": "AZ-RR-40-31 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 32.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "03 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 010 - Batch 11 - Inspection",
    "Reference": "AZ-RR-40-31 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 11.99,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "11",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 007 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 97.74,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 008 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 6.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 009 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 23.85,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 010 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 22.59,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 011 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 29.32,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "18 Jul 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 012 - Batch 12 - Inspection",
    "Reference": "AZ-RR-41-32 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 13.07,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "30 Jul 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009 - Batch 12 - Production Gloves",
    "Reference": "16477829501037350 - Huizhou Anboson Technology Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 147.72,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "30 Jul 2024",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 012 - Batch 12 - Production Gloves",
    "Reference": "16477829501037350 - Huizhou Anboson Technology Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 97.73,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "12",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "05 Aug 2024",
    "Source": "Spend Money",
    "Description": "PrimLink - CS CDS 001 - Batch 3 - Inspection",
    "Reference": "002240044 - PrimLink",
    "Currency": "GBP",
    "Debit (GBP)": 32.34,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "3",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "05 Aug 2024",
    "Source": "Spend Money",
    "Description": "PrimLink - CS CDS 002 - Batch 3 - Inspection",
    "Reference": "002240044 - PrimLink",
    "Currency": "GBP",
    "Debit (GBP)": 45.92,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "3",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "11 Aug 2024",
    "Source": "Spend Money",
    "Description": "Bari Textiles - CS CDS 001 - Batch 3 - Inspection",
    "Reference": "BTML\u2010240065\u201001 - Bari Textile",
    "Currency": "GBP",
    "Debit (GBP)": 2014.65,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "3",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "11 Aug 2024",
    "Source": "Spend Money",
    "Description": "Bari Textiles - CS CDS002 - Batch 3 - Inspection",
    "Reference": "BTML\u2010240065\u201001 - Bari Textile",
    "Currency": "GBP",
    "Debit (GBP)": 7367.92,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "3",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 - Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 301.3,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 008 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 282.29,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 010 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 2567.66,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 007 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 7505.1,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 007 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 103.98,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 008 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 7.29,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS008",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 009 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 19.26,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 010 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 25.29,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS010",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 011 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 25.54,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 012 - Batch 13 - Inspection",
    "Reference": "AZ-RR-42-40 - L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 12.74,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 011 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 5184.7,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS011",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 009 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 2484.19,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2024
  },
  {
    "Date": "06 Nov 2024",
    "Source": "Spend Money",
    "Description": "Jiangsu Guangyun Electromechanical Co., Ltd. - CS 012 -  Batch 13 - Production",
    "Reference": "PH241122 - Jiangsu Guangyun Electromechanical Co., Ltd.",
    "Currency": "GBP",
    "Debit (GBP)": 4312.36,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2024
  },
  {
    "Date": "12 Nov 2024",
    "Source": "Spend Money",
    "Description": "PrimLink - CS CDS 001 - Batch 4 - PSI",
    "Reference": "002240057 - PrimLink",
    "Currency": "GBP",
    "Debit (GBP)": 45.94,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "4",
    "SKU#": "CSCDS001",
    "Year": 2024
  },
  {
    "Date": "12 Nov 2024",
    "Source": "Spend Money",
    "Description": "PrimLink - CS CDS 002 - Batch 4 - PSI",
    "Reference": "002240057 - PrimLink",
    "Currency": "GBP",
    "Debit (GBP)": 38.82,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "4",
    "SKU#": "CSCDS002",
    "Year": 2024
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 76.53,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS008",
    "Year": 2025
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 010_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 265.31,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS010",
    "Year": 2025
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 1090.57,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 011_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 267.86,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 202.04,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "07 Jan 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 012_Batch 13_Custom Duty",
    "Reference": "FM46320D_MSC BIANCA SILVIA _TCNU2723703_UK",
    "Currency": "GBP",
    "Debit (GBP)": 133.67,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "13",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "11 Mar 2025",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009_Batch 14_Production Gloves",
    "Reference": "ABC20250311008_Huizhou Anboson Technology Co., Ltd. ",
    "Currency": "GBP",
    "Debit (GBP)": 173.79,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "11 Mar 2025",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 012_Batch 14_Production Gloves",
    "Reference": "ABC20250311008_Huizhou Anboson Technology Co., Ltd. ",
    "Currency": "GBP",
    "Debit (GBP)": 306.95,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "15 Mar 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007_Batch 14_Production Box",
    "Reference": "PI250111_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 359.94,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "15 Mar 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 011_Batch 14_Production Box",
    "Reference": "PI250111_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 440.72,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "15 Mar 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009_Batch 14_Production Box",
    "Reference": "PI250111_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 607.91,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "15 Mar 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 012_Batch 14_Production Box",
    "Reference": "PI250111_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 486.24,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "25 Apr 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 007_Batch 14_Inspection",
    "Reference": "AZ-RR-45-44_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 31.84,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "25 Apr 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 008_Batch 14_Inspection",
    "Reference": "AZ-RR-45-44_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 9.02,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS008",
    "Year": 2025
  },
  {
    "Date": "25 Apr 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 009_Batch 14_Inspection",
    "Reference": "AZ-RR-45-44_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 68.14,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "25 Apr 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 011_Batch 14_Inspection",
    "Reference": "AZ-RR-45-44_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 40.38,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "25 Apr 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 012_Batch 14_Inspection",
    "Reference": "AZ-RR-45-44_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 38.45,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "28 Apr 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 008_Batch 14_Production",
    "Reference": "PI-2503142_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 202.91,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS008",
    "Year": 2025
  },
  {
    "Date": "28 Apr 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 007_Batch 14_Production",
    "Reference": "PI-2503142_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 6142.45,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "28 Apr 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 011_Batch 14_Production",
    "Reference": "PI-2503142_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 4769.96,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "28 Apr 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 009_Batch 14_Production",
    "Reference": "PI-2503142_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 6330.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "28 Apr 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 012_Batch 14_Production",
    "Reference": "PI-2503142_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 7571.37,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "12 May 2025",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 009_Batch 14_Production Gloves",
    "Reference": "ABC20250512007_Huizhou Anboson Technology Co., Ltd. ",
    "Currency": "GBP",
    "Debit (GBP)": 263.48,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "12 May 2025",
    "Source": "Spend Money",
    "Description": "Huizhou Anboson Technology Co Ltd - CS 012_Batch 14_Production Gloves",
    "Reference": "ABC20250512007_Huizhou Anboson Technology Co., Ltd. ",
    "Currency": "GBP",
    "Debit (GBP)": 121.6,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "12 May 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 007_Batch 15_Production",
    "Reference": "PI-2505123B_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 13016.77,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "12 May 2025",
    "Source": "Spend Money",
    "Description": "JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD. - CS 009_Batch 15_Production",
    "Reference": "PI-2505123B_JIANGSU ZHIWEI ELECTROMECHANICAL CO., LTD.",
    "Currency": "GBP",
    "Debit (GBP)": 6459.19,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "26 May 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 007_Batch 15_Production Box",
    "Reference": "PI250526_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 3771.22,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "26 May 2025",
    "Source": "Spend Money",
    "Description": "Shanghai Yucai Industrial Co Ltd - CS 009_Batch 15_Production Box",
    "Reference": "PI250526_Shanghai Yucai Industrial Co Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 784.71,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "10 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008_Batch 14_Freight",
    "Reference": "FM49300_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 84.74,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS008",
    "Year": 2025
  },
  {
    "Date": "10 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007_Batch 14_Freight",
    "Reference": "FM49300_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 1322.01,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "10 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 011_Batch 14_Freight",
    "Reference": "FM49300_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 379.65,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "10 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009_Batch 14_Freight",
    "Reference": "FM49300_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 793.21,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "10 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 012_Batch 14_Freight",
    "Reference": "FM49300_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 361.58,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "13 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 008_Batch 14_Custom Duty",
    "Reference": "FM49407D_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 45.9,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS008",
    "Year": 2025
  },
  {
    "Date": "13 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 007_Batch 14_Custom Duty",
    "Reference": "FM49407D_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 716.11,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "13 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 011_Batch 14_Custom Duty",
    "Reference": "FM49407D_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 205.65,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS011",
    "Year": 2025
  },
  {
    "Date": "13 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 009_Batch 14_Custom Duty",
    "Reference": "FM49407D_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 429.67,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS009",
    "Year": 2025
  },
  {
    "Date": "13 Jun 2025",
    "Source": "Spend Money",
    "Description": "FMC Logistics - CS 012_Batch 14_Custom Duty",
    "Reference": "FM49407D_Ever Arm_DFSU6052936_UK",
    "Currency": "GBP",
    "Debit (GBP)": 195.87,
    "Credit (GBP)": 0.0,
    "Category": "Freight & Custom Duty",
    "Batch#": "14",
    "SKU#": "CS012",
    "Year": 2025
  },
  {
    "Date": "24 Jun 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 007_Batch 15_Inspection",
    "Reference": "AZ-RR-45-45_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 142.49,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS007",
    "Year": 2025
  },
  {
    "Date": "24 Jun 2025",
    "Source": "Spend Money",
    "Description": "L Victory Trading Ltd -  CS 009_Batch 15_Inspection",
    "Reference": "AZ-RR-45-45_L Victory Trading Ltd",
    "Currency": "GBP",
    "Debit (GBP)": 41.16,
    "Credit (GBP)": 0.0,
    "Category": "Manufacturing",
    "Batch#": "15",
    "SKU#": "CS009",
    "Year": 2025
  }
];