name: Scheduled Test Suite

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - e2e
          - business-logic
          - integration

jobs:
  comprehensive-tests:
    name: Comprehensive Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Setup test database
      run: |
        # Setup test database if needed
        echo "Setting up test environment..."
    
    - name: Run all tests
      if: github.event.inputs.test_type == 'all' || github.event_name == 'schedule'
      run: |
        echo "Running comprehensive test suite..."
        npx playwright test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgresql://test:test@localhost:5432/bookkeeping_test' }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret-for-ci' }}
        NEXTAUTH_URL: http://localhost:3000
        CI: true
    
    - name: Run E2E tests only
      if: github.event.inputs.test_type == 'e2e'
      run: npx playwright test tests/e2e/
    
    - name: Run business logic tests only
      if: github.event.inputs.test_type == 'business-logic'
      run: npx playwright test tests/business-logic/
    
    - name: Run integration tests only
      if: github.event.inputs.test_type == 'integration'
      run: npx playwright test tests/integration/
    
    - name: Generate test report
      if: always()
      run: |
        echo "# Scheduled Test Report - $(date)" > scheduled-test-report.md
        echo "" >> scheduled-test-report.md
        echo "## Test Summary" >> scheduled-test-report.md
        echo "- Total tests: $(find playwright-report -name "*.html" | wc -l)" >> scheduled-test-report.md
        echo "- Test type: ${{ github.event.inputs.test_type || 'all' }}" >> scheduled-test-report.md
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scheduled-test-results-${{ github.run_number }}
        path: |
          playwright-report/
          scheduled-test-report.md
        retention-days: 7
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Scheduled tests failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The scheduled test suite failed. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['test-failure', 'automated']
          });
          console.log(`Created issue #${issue.data.number}`);

  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.inputs.test_type == 'all'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli
        npm run build
        npm run start & 
        sleep 10
        lhci autorun --collect.url=http://localhost:3000 --collect.url=http://localhost:3000/bookkeeping --collect.url=http://localhost:3000/finance || true
    
    - name: Check bundle size
      run: |
        echo "## Bundle Size Report" > bundle-report.md
        echo "" >> bundle-report.md
        find .next -name "*.js" -type f -exec du -h {} + | sort -hr | head -20 >> bundle-report.md
    
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results-${{ github.run_number }}
        path: |
          .lighthouseci/
          bundle-report.md
        retention-days: 30