// Simplified action IDs for small teams (no super admin actions)
export type ActionId =
  | 'leave.approve'
  | 'leave.reject'
  | 'leave.cancel'
  | 'policy.acknowledge'
  | 'review.start'
  | 'review.submit'
  | 'review.hrApprove'
  | 'review.hrReject'
  | 'review.acknowledge'
  | 'disciplinary.hrApprove'
  | 'disciplinary.hrReject'
  | 'disciplinary.acknowledge'
  | 'disciplinary.appeal'
  | 'disciplinary.appeal.hrDecide'
  | 'task.markDone'
  | 'task.markInProgress'
