# Reusable CI workflow for Node.js applications
name: Reusable CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '18'
      run-tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: true
      run-prisma:
        description: 'Run Prisma commands'
        required: false
        type: boolean
        default: false

jobs:
  lint-and-type:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client
      if: ${{ inputs.run-prisma }}
      run: npx prisma generate
      
    - name: Run linting
      run: npm run lint --if-present
      
    - name: Run type checking
      run: npm run typecheck --if-present
      
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint-and-type
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client
      if: ${{ inputs.run-prisma }}
      run: npx prisma generate
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          .next/
          out/
          dist/
          build/
        retention-days: 1
        
  test:
    name: Run Tests
    if: ${{ inputs.run-tests }}
    runs-on: ubuntu-latest
    needs: lint-and-type
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma client
      if: ${{ inputs.run-prisma }}
      run: npx prisma generate
      
    - name: Run tests
      run: npm test --if-present