name: CD (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or commit SHA to deploy"
        required: false
        default: "main"

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-prod-base.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit
