name: CD

on:
  pull_request_target:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-prod-base.yml
    with:
      ref: ''
    secrets: inherit
