name: PR Policy

on:
  pull_request:
    branches: [ main ]

jobs:
  require-dev-source:
    name: Require PR head to be dev
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          echo "Base: ${{ github.base_ref }}"
          echo "Head: ${{ github.head_ref }}"
          if [ "${{ github.base_ref }}" != "main" ]; then
            echo "Not targeting main; skipping."
            exit 0
          fi
          echo "::warning::PR policy enforcement is currently disabled; allowing '${{ github.head_ref }}' → main."
