name: 'Architect Agent PR Review & Correction'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: 'Run Architect Agent'
        run: |
          claude -p "You are the Architect Agent. Your constitution is in ./docs/CLAUDE_ARCHITECT.md. Review and actively correct Pull Request #${{ github.event.pull_request.number }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}